<?= $this->doctype(); ?>
<html lang="PT-BR">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Érica & Diego</title>
        <link rel="icon" href="img/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" href="css/jquery.fancybox.css" type="text/css" media="screen">
        <link rel="stylesheet" href="css/bootstrap.css" type="text/css" media="screen">
        <link rel="stylesheet" href="css/style.css" type="text/css" media="screen">
        <script type="text/javascript" src="js/include_script.js"></script>
        <!--[if lt IE 8]><div style='text-align:center'><a href="http://www.microsoft.com/windows/internet-explorer/default.aspx?ocid=ie6_countdown_bannercode"><img src="http://www.theie6countdown.com/img/upgrade.jpg"border="0"alt=""/></a></div><![endif]-->
        <!--[if lt IE 9]>
        <link rel="stylesheet" href="css/docs.css" type="text/css" media="screen">
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <link href="css/ie.css" rel="stylesheet" type="text/css">
        <![endif]-->
    </head>
    <body>
        <?= $this->layout()->content; ?>
    </body>
    </html>
