<!--web site spinner-->
<div id="webSiteLoader"></div>
<!--button back top-->
<div id="back-top"></div>
<!--page spinner-->
<div id="pageLoader">
    <div></div>
</div>
<img class="image_resize" src="img/bg_pic.jpg" alt="">
<!--content wrapper-->
<div id="wrapper">
    <!--header-->
    <header>
        <!--logo and company name-->
        <div class="container">
            <div class="row">
                <div class="span24">
                    <h1><a href="index.html"><img src="img/logo.png" alt>michael & valerie wedding album</a></h1>
                    <!--menu-->
                    <div class="navbar">
                        <div class="navbar-inner">
                            <ul class="sf-menu">
                                <li><a href="index.html"><span>main</span></a></li>
                                <li><a href="index-1.html"><span>love story</span></a></li>
                                <li><a href="index-2.html"><span>guest wishes</span></a></li>
                                <li><a href="index-3.html"><span>gallery</span><em></em></a>
                                    <ul class="nav sub-menu">
                                        <li><a href="index-6.html">gallery 1</a></li>
                                        <li><a href="index-6.html">gallery 2</a>
                                            <ul class="nav sub-menu">
                                                <li><a href="index-6.html">Lorem ipsum</a></li>
                                                <li><a href="index-6.html">dolor sit</a></li>
                                                <li class="last"><a href="index-6.html">adipiscing</a></li>
                                            </ul>
                                        </li>
                                        <li class="last"><a href="index-6.html">gallery 3</a></li>
                                    </ul>
                                </li>
                                <li class="last"><a href="index-4.html"><span>contacts</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!--content-->
    <div class="splash">
        <div class="carouselHolder">
            <div class="carousel">
                <ul>
                    <li><img src="img/page1_pic1.jpg" alt></li>
                    <li><img src="img/page1_pic2.jpg" alt></li>
                    <li><img src="img/page1_pic3.jpg" alt></li>
                    <li><img src="img/page1_pic4.jpg" alt></li>
                    <li><img src="img/page1_pic5.jpg" alt></li>
                    <li><img src="img/page1_pic6.jpg" alt></li>
                </ul>
            </div>
            <a href="#" class="nextBtn"><span></span></a>
            <a href="#" class="prevBtn"><span></span></a>

            <div class="shadowLeft"></div>
            <div class="shadowRight"></div>
        </div>
    </div>
    <section class="container">
        <div>
            <div class="dynamicContent"></div>
        </div>
    </section>
    <!--footer-->
    <footer>
        <div class="container">
            <div class="row">
                <div class="span12">
                    <p>Érica & Diego &copy; 2014 | <a href="index-5.html">Privacy Policy</a></p>
                    <!-- {%FOOTER_LINK} -->
                </div>
                <div class="span12">
                    <div class="socIconsHolder">
                        <ul class="soc_icons">
                            <li><a href="#"><img src="img/soc_icon1.png" alt></a></li>
                            <li><a href="#"><img src="img/soc_icon2.png" alt></a></li>
                            <li><a href="#"><img src="img/soc_icon3.png" alt></a></li>
                        </ul>
                        <p>get in touch with us</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>
<script type="text/javascript" src="js/bootstrap.js"></script>
<!-- coded by Smart -->
<!--LIVEDEMO_00 -->
